version: '3.8'

services:
  app:
    image: node:alpine
    working_dir: /ws
    volumes:
    - .:/ws
    ports:
    - 5000:5000
    entrypoint: /bin/sh -c 'tail -f'
    environment:
      HOST: 0.0.0.0
      PORT: 5000
